        // Seleciona o input de CDD e o campo de gênero
        const cddInput = document.getElementById('cdd');
        const genreInput = document.getElementById('genre');

        // Cria um objeto que mapeia CDDs para gêneros
        const cddToGenre = {
            '000': 'Generalidades',
            '001': 'Conhecimento',
            '001.2': 'Erudição',
            '001.4': 'Pesquisa; Métodos estatísticos',
            '001.42': 'Metodologia da pesquisa',
            '001.422': 'Métodos estatísticos',
            '001.424': 'Pesquisa Operacional',
            '001.43': 'Métodos históricos, descritivos e experimentais',
            '001.434': 'Métodos experimentais',
            '001.44': 'Suporte e incentivos para a pesquisa',
            '002': 'Livro',
            '003': 'Sistemas',
            '004': 'Sistemas de Processamento de dados e Ciência da computação',
            '004.678': 'Internet',
            '005': 'Programação de computadores, programas e dados',
            '006': 'Métodos computacionais especiais',
            '010': 'Bibliografia',
            '011': 'Bibliografias',
            '012': 'Bibliografias (Indivíduos)',
            '014': 'Obras anônimas e pseudônimos',
            '015': 'Bibliografias de trabalhos de lugares específicos',
            '016': 'Bibliografias de trabalhos sobre temas específicos',
            '017': 'Catálogos gerais sujeitos',
            '018': 'Catálogos organizados por autor, data, etc',
            '019': 'Catálogos Dicionário',
            '020': 'Biblioteca & Ciências da Informação',
            '020.202': 'Bibliotecas – Manuais, Guias, etc.',
            '020.23': 'Bibliotecários',
            '020.285': 'Bibliotecas e Ciências da Informação – Processamento de dados',
            '020.3': 'Dicionários de Biblioteconomia',
            '020.7': 'Biblioteconomia – Estudo e Ensino',
            '020.9': 'História da Biblioteconomia e Ciência da Informação',
            '021': 'Bibliotecas e Sociedade',
            '021.2': 'Bibliotecas – Relações com a comunidade',
            '021.64': 'Bibliotecas – Cooperação',
            '022': 'A administração de instalações físicas',
            '023': 'Gestão de pessoal',
            '023.4': 'Bibliotecas – Administração de pessoal',
            '025': 'Operações de biblioteca',
            '025.00285': 'Bibliotecas – Processamento de dados',
            '025.04': 'Automação de bibliotecas',
            '025.1': 'Administração de Bibliotecas',
            '025.17': 'Multimeios',
            '025.21': 'Desenvolvimento de coleções',
            '025.3': 'Catalogação e Indexação',
            '025.31': 'Análise e controle bibliográfico – Catálogos',
            '025.316': 'Formatos MARC',
            '025.32': 'Análise e Controle bibliográfico – Catalogação descritiva',
            '025.34': 'Multimeios – Indexação',
            '025.347': 'Fotografia – Indexação',
            '025.4': 'Análise e controle de assunto',
            '025.42': 'Classificação',
            '025.43': 'Classificações bibliográficas',
            '025.431': 'Classificação Decimal de Dewey',
            '025.432': 'Classificação Decimal Universal',
            '025.5': 'Serviços para usuários',
            '025.52': 'Serviços de referência e informação',
            '025.525': 'Disseminação Seletiva da Informação (DSI)',
            '026': 'Bibliotecas especializadas',
            '026.61': 'Bibliotecas da área de saúde',
            '027': 'Bibliotecas, Arquivos e Centros de Informação em geral',
            '027.009': 'História das Bibliotecas',
            '027.009621': 'História das Bibliotecas – Egito',
            '027.081': 'História das Bibliotecas – Brasil',
            '027.1': 'Bibliotecas particulares',
            '027.4': 'Bibliotecas públicas',
            '027.481': 'Bibliotecas públicas brasileiras',
            '027.573': 'Bibliotecas governamentais – Estados Unidos',
            '027.581': 'Bibliotecas nacionais – Brasil',
            '027.6': 'Bibliotecas para grupos e Organizações especiais',
            '027.662': 'Bibliotecas de Hospitais',
            '027.663': 'Bibliotecas para portadores de necessidades especiais',
            '027.69': 'Bibliotecas de negócios e Organizações industriais',
            '027.7': 'Bibliotecas de Faculdades e Universidades',
            '027.781': 'Bibliotecas universitárias – Brasil',
            '027.8': 'Bibliotecas escolares',
            '028': 'Leitura e utilização de outros meios de informação',
            '028.7': 'Fontes de informação',
            '028.72': 'Leitura – Pesquisa',
            '028.9': 'Interesses na leitura',
            '030': 'Obras enciclopédicas Gerais',
            '031': 'Enciclopédias em Inglês Americano',
            '032': 'Enciclopédias em Inglês',
            '033': 'Em outras línguas germânicas',
            '034': 'Enciclopédias em francês, occitano e catalão',
            '035': 'Enciclopédias em italiano, romeno e línguas relacionadas',
            '036': 'Enciclopédias em Espanhol e Português',
            '037': 'Enciclopédias em línguas eslavas',
            '038': 'Enciclopédias em línguas escandinavas',
            '039': 'Enciclopédias em outros idiomas',
            '050': 'Publicações seriadas em geral',
            '051': 'Publicações Seriadas em Inglês Americano',
            '052': 'Publicações Seriadas em Inglês',
            '053': 'Publicações Seriadas em outras línguas germânicas',
            '054': 'Publicações Seriadas em francês, occitano e catalão',
            '055': 'Publicações Seriadas em italiano, romeno e relacionados',
            '056': 'Seriados em Espanhol e Português',
            '057': 'Seriados em línguas eslavas',
            '058': 'Seriados em línguas escandinavas',
            '059': 'Seriados em outros idiomas',
            '060': 'Organizações Gerais e Museologia',
            '061': 'Organizações na América do Norte',
            '062': 'Organizações na Ilhas Britânicas; na Inglaterra',
            '063': 'Organizações na Europa central; na Alemanha',
            '064': 'Organizações na França & Mónaco',
            '065': 'Organizações na Itália e ilhas adjacentes',
            '066': 'Organizações na Península Ibérica e ilhas adjacentes',
            '067': 'Organizações na Europa Oriental; na Rússia',
            '068': 'Organizações em outras áreas geográficas',
            '069': 'Museologia',
            '070': 'Notícias da mídia, jornalismo e editoração',
            '070.4': 'Jornalismo',
            '071': 'Jornal na América do Norte',
            '072': 'Jornal nas Ilhas Britânicas; na Inglaterra',
            '073': 'Jornais na Europa central; na Alemanha',
            '074': 'Jornais na França & Mônaco',
            '075': 'Jornal na Itália e ilhas adjacentes',
            '076': 'Na Península Ibérica e ilhas adjacentes',
            '077': 'Jornal na Europa Oriental; na Rússia',
            '078': 'Jornal na Escandinávia',
            '079': 'Jornais em outras áreas geográficas',
            '080': 'Coleções gerais',
            '081': 'Coleções em Inglês Americano',
            '082': 'Coleções em Inglês',
            '083': 'Coleções em outras línguas germânicas',
            '084': 'Coleções em francês, occitano e catalão',
            '085': 'Coleções em italiano, romeno e línguas relacionadas',
            '086': 'Coleções em Espanhol e Português',
            '087': 'Coleções em línguas eslavas',
            '088': 'Coleções em línguas escandinavas',
            '089': 'Coleções em outros idiomas',
            '090': 'Manuscritos e livros raros',
            '091': 'Manuscritos',
            '092': 'Livros Bloco',
            '093': 'Incunábulos',
            '094': 'Livros',
            '095': 'Livros notáveis (Associações/Ligações)',
            '096': 'Livros notáveis (Ilustrações)',
            '097': 'Livros notáveis (Posse ou origem)',
            '098': 'Obras proibidas, falsificações e fraudes',
            '099': 'Livros notáveis (Formato)',

            '100': 'Filosofia',
            '101': 'Teoria da filosofia',
            '102': 'Miscelânea',
            '103': 'Dicionários e Enciclopédias',
            '105': 'Publicações seriadas',
            '106': 'Organizações e gestão',
            '107': 'Educação, pesquisa e tópicos relacionados',
            '108': 'Pessoas – Filosofia',
            '109': 'História da Filosofia',
            '110': 'Metafísica',
            '111': 'Ontologia',
            '113': 'Cosmologia',
            '114': 'Espaço',
            '115': 'Tempo',
            '116': 'Mudança / Variação',
            '117': 'Estrutura',
            '118': 'Força e energia',
            '119': 'Número e quantidade',
            '120': 'Epistemologia, causalidade e humanidade',
            '121': 'Epistemologia',
            '122': 'Causalidade',
            '123': 'Determinismo e indeterminismo',
            '124': 'Teleologia',
            '126': 'O Eu',
            '127': 'O inconsciente e subconsciente',
            '128': 'Humanidade',
            '129': 'Origem e destino das almas individuais',
            '130': 'Parapsicologia e ocultismo',
            '131': 'Métodos (Parapsicologia & ocultismo)',
            '133': 'Tópicos específicos em parapsicologia e ocultismo',
            '135': 'Sonhos e mistérios',
            '137': 'Grafologia Divinatória',
            '138': 'Fisionomia',
            '139': 'Frenologia',
            '140': 'Escolas filosóficas específicas',
            '141': 'Sistemas de idealismo e afins',
            '142': 'Filosofia crítica',
            '142.78': 'Existencialismo',
            '143': 'Bergsonismo & intuitivismo',
            '144': 'Humanismo e sistemas relacionados',
            '145': 'Sensacionalismo',
            '146': 'Naturalismo & sistemas relacionados',
            '147': 'Panteísmo & sistemas relacionados',
            '148': 'Ecletismo, liberalismo e tradicionalismo',
            '149': 'Outros sistemas filosóficos',
            '150': 'Psicologia',
            '150.1': 'Psicologia – Filosofia',
            '150.192': 'Psicologia fenomenológica',
            '150.1954': 'Psicologia Junguiana',
            '150.1982': 'Psicologia da Gestalt',
            '150.1986': 'Psicologia humanística',
            '150.21': 'Estatística em Psicologia',
            '150.23': 'Psicologia como profissão',
            '150.3': 'Dicionários de Psicologia',
            '150.7': 'Psicologia – Estudo e Ensino',
            '150.9': 'História da Psicologia',
            '150.92': 'Psicólogos',
            '152': 'Percepção, movimento, emoções e conduções',
            '152.3845': 'Psicologia do desenho',
            '153': 'Processos mentais e inteligência',
            '153.15': 'Aprendizagem',
            '154': 'Estados subconscientes e alterados',
            '155': 'Psicologia diferencial e do desenvolvimento',
            '155.2': 'Psicologia individual',
            '155.4': 'Psicologia infantil',
            '155.4092': 'Psicólogos infantis',
            '155.4123': 'Capacidade motora',
            '155.413': 'Criança – Inteligência',
            '155.422': 'Psicologia da primeira infância',
            '155.5': 'Psicologia de jovens de 12 a 20 anos',
            '155.53': 'Psicologia de jovens de 12 a 20 anos por sexo',
            '155.532': 'Psicologia do adolescente',
            '155.632': 'Psicologia masculina',
            '155.633': 'Psicologia feminina',
            '155.8': 'Psicologia étnica (Diversidade étnica)',
            '155.84': 'Psicologia de grupos étnicos específicos',
            '155.8981': 'Psicologia brasileira (Características nacionais brasileiras)',
            '155.9': 'Psicologia ambiental',
            '155.91145': 'Psicologia da cor',
            '156': 'Psicologia comparada',
            '156.283': 'Psicologia experimental',
            '158': 'Psicologia aplicada',
            '158.7': 'Psicologia industrial',
            '158.7023': 'Psicologia do trabalho',
            '160': 'Lógica',
            '161': 'Indução',
            '162': 'Dedução',
            '165': 'Falácias e fontes de erro',
            '166': 'Silogismos',
            '167': 'Hipóteses',
            '168': 'Argumento e persuasão',
            '169': 'Analogia',
            '170': 'Ética',
            '171': 'Sistemas éticos',
            '172': 'Ética política',
            '173': 'Ética das relações familiares',
            '174': 'Ética profissional',
            '175': 'Ética de recreação e lazer',
            '176': 'Ética do sexo e reprodução',
            '177': 'Ética das relações sociais',
            '178': 'Ética do consumo',
            '179': 'Outras normas éticas',
            '180': 'Filosofia antiga e medieval',
            '181': 'Filosofia oriental',
            '182': 'Filosofias gregas pré-socráticas',
            '183': 'Filosofias socráticas e relacionados',
            '184': 'Filosofia platônica',
            '185': 'Filosofia aristotélica',
            '186': 'Ceticismo e filosofias neoplatônicas',
            '187': 'Filosofia epicurista',
            '188': 'Filosofia estóica',
            '189': 'Filosofia ocidental medieval',
            '190': 'Filosofia ocidental moderna',
            '191': 'Filosofia dos Estados Unidos e Canadá',
            '192': 'Filosofia das Ilhas Britânicas',
            '193': 'Filosofia da Alemanha e Áustria',
            '194': 'Filosofia da França',
            '195': 'Filosofia da Itália',
            '196': 'Filosofia da Espanha e Portugal',
            '197': 'Filosofia da ex-União Soviética',
            '198': 'Filosofia da Escandinávia',
            '199': 'Filosofia em outras áreas geográficas',

            '200': 'Religião',
            '201': 'Mitologia religiosa e teologia sociais',
            '202': 'Doutrinas',
            '203': 'Culto público e outras práticas',
            '204': 'A experiência religiosa, vida e prática',
            '205': 'Ética religiosa',
            '206': 'Líderes e organizações religiosas',
            '207': 'Missões e educação religiosa',
            '208': 'Fontes',
            '209': 'Seitas e movimentos de reforma',
            '210': 'Filosofia e Teoria da religião',
            '211': 'Conceitos de Deus',
            '212': 'Cognoscibilidade e atributos divinos',
            '213': 'Criação',
            '214': 'Teodiceia (Doutrina da justiça divina)',
            '215': 'Ciência e religião',
            '218': 'Humanidade (Gênero humano)',
            '220': 'Bíblia',
            '221': 'Antigo Testamento (Tanakh)',
            '222': 'Livros históricos do Antigo Testamento',
            '223': 'Livros poéticos do Antigo Testamento',
            '224': 'Livros proféticos do Antigo Testamento',
            '225': 'Novo Testamento',
            '226': 'Evangelhos e Atos',
            '227': 'Epístolas',
            '228': 'Revelação (Apocalipse)',
            '229': 'Livros apócrifos e pseudoepígrafes',
            '230': 'Cristianismo e Teologia cristã',
            '231': 'Deus',
            '232': 'Jesus Cristo e sua família',
            '233': 'Humanidade',
            '234': 'Salvação e graça',
            '235': 'Seres espirituais',
            '236': 'Escatologia',
            '238': 'Credos e Catecismos',
            '239': 'Apologética e polêmicas',
            '240': 'Teologia moral e devocional cristã',
            '241': 'Ética cristã',
            '242': 'Literatura devocional',
            '243': 'Textos evangelísticos para os indivíduos',
            '246': 'Uso da arte no Cristianismo',
            '247': 'Artigos e mobiliário de Igreja',
            '248': 'Experiência, prática e vida cristã',
            '249': 'Observâncias cristãs na vida familiar',
            '250': 'Prática cristã & Igrejas locais',
            '251': 'Pregação',
            '252': 'Textos de sermões',
            '253': 'Ofício e trabalho pastoral',
            '253.52': 'Psicologia pastoral',
            '254': 'Administração paroquial',
            '255': 'Congregações & Ordens religiosas',
            '259': 'Cuidado pastoral familiar e para outros grupos de pessoas',
            '260': 'Teologia social e eclesiástica',
            '261': 'Teologia social',
            '262': 'Eclesiologia',
            '263': 'Dias, horários e locais de observância',
            '264': 'Cultos públicos',
            '265': 'Sacramentos, outros ritos e atos',
            '266': 'Missões',
            '267': 'Associações de trabalho religioso',
            '268': 'Educação religiosa',
            '269': 'Renovação espiritual',
            '270': 'História do Cristianismo e da Igreja cristã',
            '271': 'Ordens religiosas na história da igreja',
            '272': 'Perseguições na história da igreja',
            '273': 'Controvérsias doutrinárias e heresias',
            '274': 'História do Cristianismo na Europa',
            '275': 'História do Cristianismo na Ásia',
            '276': 'História do Cristianismo na África',
            '277': 'História do Cristianismo na América do Norte',
            '278': 'História do Cristianismo na América do Sul',
            '279': 'História do Cristianismo em outras áreas',
            '280': 'Denominações cristãs e seitas',
            '281': 'Igrejas primitivas e Igrejas orientais',
            '282': 'Igreja Católica Romana',
            '283': 'Igrejas Anglicanas',
            '284': 'Igrejas Protestantes de origem Continental',
            '285': 'Igreja Presbiteriana, Reformada e Congregacional',
            '286': 'Igreja Batista, Discípulos de Cristo (Apostólica) e Adventista',
            '287': 'Igreja Metodista e afins',
            '289': 'Outras denominações e Seitas',
            '290': 'Outras religiões',
            '292': 'Religião grega e romana',
            '293': 'Religião germânica',
            '294': 'Religiões de origem indiana',
            '295': 'Zoroastrismo',
            '296': 'Judaísmo',
            '297': 'Islamismo, Babismo & Fé Bahai',
            '299': 'Religiões não previstas para outros lugares',

            '300': 'Ciências Sociais',
            '300.72': 'Pesquisa social',
            '301': 'Sociologia e antropologia',
            '301.350981': 'Sociologia e antropologia – Brasil',
            '301.021': 'Pesquisa sociológica',
            '301.1': 'Psicologia social',
            '302': 'Interação social',
            '303': 'Processos sociais',
            '304': 'Fatores que afetam o comportamento social',
            '305': 'Grupos sociais',
            '306': 'Cultura e instituições',
            '306.09': 'História social',
            '307': 'Comunidades',
            '310': 'Estatísticas Gerais',
            '314': 'Estatística geral da Europa',
            '315': 'Estatística geral da Ásia',
            '316': 'Estatística geral da África',
            '317': 'Estatística geral da América do Norte',
            '318': 'Estatística geral da América do Sul',
            '319': 'estatísticas gerais de outras áreas',
            '320': 'Ciência Política',
            '320.019': 'Psicologia política',
            '321': 'Sistemas de Governo e Estado',
            '321.3': 'Feudalismo',
            '321.4': 'Democracia',
            '322': 'Relações de Estado a grupos organizados',
            '323': 'Direitos civis e políticos',
            '324': 'Processo político',
            '325': 'Migração internacional e colonização',
            '326': 'Escravidão e emancipação',
            '327': 'Relações internacionais',
            '328': 'Processo legislativo',
            '330': 'Economia',
            '331': 'Economia do trabalho',
            '332': 'Economia financeira',
            '333': 'Economia da terra e energia',
            '334': 'Cooperativas',
            '335': 'Socialismo & Sistemas relacionados',
            '335.2': 'Socialismo utópico',
            '335.4': 'Sistemas Marxistas',
            '335.43': 'Comunismo',
            '335.434': 'Outros Sistemas Sociais relacionados',
            '336': 'Finanças públicas',
            '337': 'Economia Internacional',
            '338': 'Produção',
            '338.98106': 'Produção científica',
            '339': 'Macroeconomia e tópicos relacionados',
            '340': 'Direito',
            '340.1502': 'Psicologia forense',
            '341': 'Lei das nações',
            '342': 'Direito Constitucional e Administrativo',
            '342.28': 'Direito autoral',
            '343': 'Direito Militar, Tributário, Comercial e Industrial',
            '344': 'Direito do Trabalho, Social, Educacional e cultural',
            '345': 'Direito Penal',
            '346': 'Direito Privado',
            '347': 'Processo Civil & Tribunais',
            '348': 'Leis, Regulamentos e Casos',
            '349': 'Leis de jurisdições e áreas específicas',
            '350': 'Administração Pública e Ciência Militar',
            '351': 'Administração Pública',
            '352': 'Considerações gerais da Administração Pública',
            '353': 'Campos específicos da Administração Pública',
            '354': 'Administração da Economia e do Meio Ambiente',
            '355': 'Ciência militar',
            '356': 'Forças de infantaria e estado de guerra',
            '357': 'Forças montadas e estado de guerra',
            '358': 'Força Aérea & outras forças especializadas',
            '359': 'Força Marítima/Marinha e estado de guerra',
            '360': 'Problemas sociais, serviços e associações',
            '361': 'Problemas sociais e bem-estar social em geral',
            '362': 'Problemas e serviços de bem-estar social',
            '363': 'Outros problemas e serviços sociais',
            '363.70071': 'Educação ambiental',
            '364': 'Criminologia',
            '365': 'Penal e instituições afins',
            '366': 'Associações',
            '367': 'Clubes Gerais',
            '368': 'Seguro',
            '369': 'Tipos diversos de Associações',
            '370': 'Educação',
            '370.0981': 'Educação – Brasil',
            '370.15': 'Psicologia educacional',
            '370.152': 'Cognição',
            '370.1522': 'Memória',
            '370.15651': 'Psicologia da aprendizagem – Matemática',
            '370.156': 'Psicologia da aprendizagem de assuntos específicos',
            '370.1931': 'Educação comunitária',
            '370.195': 'Educação comparada',
            '370.98131': 'Educação – Ceará',
            '371': 'Escolas e suas atividades; Educação especial',
            '371.26': 'Avaliação educacional',
            '371.335': 'Educação, imagem e mídias',
            '371.358': 'Educação à distância em meio eletrônico, teleensino e conferências',
            '371.71': 'Educação em saúde',
            '371.9': 'Educação especial',
            '372': 'Ensino elementar',
            '372.21': 'Educação pré-escolar',
            '372.4': 'Leitura (Ensino Fundamental)',
            '372.7': 'Matemática (Ensino Fundamental)',
            '372.86': 'Educação física para crianças',
            '373': 'Ensino secundário',
            '374': 'Educação de adultos',
            '374.4': 'Educação à distância (Adultos)',
            '375': 'Currículos',
            '378': 'Ensino Superior',
            '378.0981': 'Ensino Superior – Brasil',
            '379': 'Políticas públicas em educação',
            '380': 'Comércio, comunicação e transporte',
            '381': 'Comércio',
            '382': 'Comércio internacional',
            '383': 'Comunicação Postal',
            '384': 'Comunicação & Telecomunicação',
            '385': 'Transporte ferroviário',
            '386': 'Transporte fluvial e de barco',
            '387': 'Transporte hidroviário, aéreo e espacial',
            '388': 'Transportes; Transporte terrestre',
            '389': 'Metrologia e Normalização',
            '390': 'Costumes, etiqueta e folclore',
            '391': 'Trajes e aparência pessoal',
            '392': 'Costumes do ciclo de vida & vida doméstica',
            '393': 'Costumes da Morte',
            '394': 'Costumes em geral',
            '395': 'Etiqueta (Conduta)',
            '398': 'Folclore',
            '398.0981': 'Folclore – Brasil',
            '398.5': 'Literatura de Cordel',
            '399': 'Costumes de guerra e diplomacia',

            '400': 'Linguagem & Idiomas',
            '401': 'Filosofia e teoria da linguagem',
            '402': 'Miscelânea',
            '403': 'Dicionários e Enciclopédias',
            '404': 'Tópicos especiais',
            '405': 'Publicações em série',
            '406': 'Organizações e gestão (Linguagem e Educação)',
            '407': 'Educação, pesquisa e tópicos relacionados',
            '408': 'Tratamento da linguagem no que diz respeito ao tipo de pessoas',
            '409': 'Linguagem – Tratamento geográfico e de pessoas',
            '410': 'Linguística geral',
            '411': 'Sistemas de escrita',
            '412': 'Etimologia',
            '413': 'Dicionários',
            '414': 'Fonologia e fonética',
            '415': 'Gramática',
            '417': 'Dialetologia e linguística histórica',
            '418': 'Norma culta (Uso padrão) & Linguística aplicada',
            '419': 'Línguas de Sinais',
            '420': 'Língua inglesa',
            '421': 'Sistema de escrita em Inglês e fonologia',
            '422': 'Inglês (Etimologia)',
            '423': 'Dicionários de inglês',
            '425': 'Gramática da Língua Inglesa',
            '427': 'Variações do idioma Inglês',
            '428': 'Norma culta/Uso Padrão da Língua Inglesa',
            '429': 'Inglês Antigo (Anglo-saxão)',
            '430': 'Línguas germânicas; Alemão',
            '431': 'Sistemas de escrita alemão e fonologia',
            '432': 'Etimologia alemã',
            '433': 'Dicionários alemães',
            '435': 'Gramática alemã',
            '437': 'Variações da língua alemã',
            '438': 'Norma culta/Uso padrão do alemão',
            '439': 'Outras línguas germânicas',
            '440': 'Línguas românicas; Francês',
            '441': 'Sistemas de escrita franceses e fonologia',
            '442': 'Etimologia (Francês)',
            '443': 'Dicionários franceses',
            '445': 'Gramática francesa',
            '447': 'Variações da língua francesa',
            '448': 'Norma culta/Uso padrão do francês',
            '449': 'Occitano e Catalão',
            '450': 'Língua italiana, romena e outras relacionadas',
            '451': 'Sistemas de escrita italiana e fonologia',
            '452': 'Etimologia (Italiana)',
            '453': 'Dicionários italianos',
            '455': 'Gramática italiana',
            '457': 'Variações da língua italiana',
            '458': 'Norma culta/Uso padrão do Italiano',
            '459': 'Língua romena e outras relacionadas',
            '460': 'Língua espanhola e Português',
            '461': 'Sistema de escrita espanhol e fonologia',
            '462': 'Etimologia (Espanhol)',
            '463': 'Dicionários de espanhol',
            '465': 'Gramática espanhola',
            '467': 'Variações da língua espanhola',
            '468': 'Norma culta/Uso padrão do espanhol',
            '469': 'Português/Língua Portuguesa',
            '470': 'Línguas itálicas; Línguas latinas; Latim',
            '471': 'Escrita clássica latina e fonologia',
            '472': 'Etimologia clássica latina',
            '473': 'Dicionários latinos clássicos',
            '475': 'Gramática latina clássica',
            '477': 'Latim Antigo, pós-clássico e vulgar',
            '478': 'Uso clássico do Latim',
            '479': 'Outras línguas itálicas',
            '480': 'Línguas helênicas; Grego clássico',
            '481': 'Escrita clássica grega e fonologia',
            '482': 'Etimologia clássica grega',
            '483': 'Dicionários clássicos de grego',
            '485': 'Gramática clássica grega',
            '487': 'Grego Pré-Clássico e Pós-clássico',
            '488': 'Uso do grego clássico',
            '489': 'Outras línguas helênicas',
            '490': 'Outros idiomas',
            '491': 'Línguas indo-europeias do leste e Celtas',
            '492': 'Línguas afro-asiáticas; Línguas semíticas',
            '493': 'Línguas afro-asiáticas não-semitas',
            '494': 'Altaica, Urálica, Hiperbórea e Dravidiano',
            '495': 'Línguas do Oriente e Sudeste da Ásia',
            '496': 'Línguas Africanas',
            '497': 'Línguas nativas da América do Norte',
            '498': 'Línguas nativas da América do Sul',
            '499': 'Línguas austronesianas & outras',

            '500': 'Ciências Naturais e Matemáticas',
            '501': 'Filosofia e teoria (Matemática)',
            '502': 'Miscelânea',
            '503': 'Dicionários e Enciclopédias (Ciências e Matemática)',
            '505': 'Publicações em série (Ciências e Matemática)',
            '506': 'Organizações e gestão (Ciências e Matemática)',
            '507': 'Educação, pesquisa e tópicos relacionados (Ciências e Matemática)',
            '508': 'História natural',
            '509': 'História, Geografia e pessoas (Ciências e Matemática)',
            '510': 'Matemática',
            '511': 'Princípios gerais de matemática',
            '512': 'Álgebra',
            '513': 'Aritmética',
            '514': 'Topologia',
            '515': 'Análise',
            '516': 'Geometria',
            '518': 'Análise numérica',
            '519': 'Probabilidades e matemática aplicada',
            '520': 'Astronomia e ciências relacionadas',
            '521': 'Mecânica Celeste',
            '522': 'Técnicas, equipamentos e materiais',
            '523': 'Corpos e fenômenos celestes específicos',
            '525': 'Terra (Geografia astronômica)',
            '526': 'Geografia Matemática',
            '527': 'Navegação Celestial',
            '528': 'Efemérides',
            '529': 'Cronologia',
            '530': 'Física',
            '531': 'Mecânica Clássica; Mecânica dos sólidos',
            '532': 'Mecânica dos Fluidos; Mecânica de líquidos',
            '533': 'Mecânica de gás',
            '534': 'Sons & vibrações relacionadas',
            '535': 'Luz & fenômenos infravermelhos e ultravioletas',
            '536': 'Calor',
            '537': 'Eletricidade e eletrônica',
            '538': 'Magnetismo',
            '539': 'A física moderna',
            '540': 'Química e ciências relacionadas',
            '541': 'Físico-química',
            '542': 'Técnicas, equipamentos e materiais',
            '543': 'Química analítica',
            '546': 'Química inorgânica',
            '547': 'Química Orgânica',
            '548': 'Cristalografia',
            '549': 'Mineralogia',
            '550': 'Ciências da Terra e Geociências',
            '551': 'Geologia, hidrologia e meteorologia',
            '552': 'Petrologia',
            '553': 'Geologia Econômica',
            '554': 'Ciências da Terra da Europa',
            '555': 'Ciências da Terra da Ásia',
            '556': 'Ciências da Terra da África',
            '557': 'Ciências da Terra da América do Norte',
            '558': 'Ciências da Terra da América do Sul',
            '559': 'Ciências da Terra de outras áreas',
            '560': 'Paleontologia; Paleozoologia',
            '561': 'Paleobotânica; Micro-organismos fósseis',
            '562': 'Fósseis invertebrados',
            '563': 'Fósseis marinhos e invertebrados do litoral',
            '564': 'Fósseis de moluscos',
            '565': 'Fósseis de artrópodes',
            '566': 'Fósseis cordados',
            '567': 'Fósseis vertebrados de sangue frio; Fósseis de peixes',
            '568': 'Fósseis de aves',
            '569': 'Fósseis de mamíferos',
            '570': 'Ciências da vida; Biologia',
            '571': 'Fisiologia e Assuntos Relacionados',
            '572': 'Bioquímica',
            '573': 'Sistemas fisiológicos específicos em animais',
            '574': 'Biologia',
            '575': 'Partes específicas de Sistemas em plantas',
            '576': 'Genética e Evolução',
            '577': 'Ecologia',
            '578': 'História natural dos organismos',
            '579': 'Micro-organismos, fungos e algas',
            '580': 'Plantas (Botânica)',
            '581': 'Tópicos específicos em História natural',
            '582': 'Plantas conhecidas por características e flores',
            '583': 'Dicotiledôneas',
            '584': 'Monocotiledôneas',
            '585': 'Gimnospermas; Coníferas',
            '586': 'Plantas sem sementes',
            '587': 'Plantas vasculares sem sementes',
            '588': 'Briófitas',
            '590': 'Animais (Zoologia)',
            '591': 'Tópicos específicos em história natural',
            '592': 'Invertebrados',
            '593': 'Animais marinhos e invertebrados',
            '594': 'Moluscos',
            '595': 'Artrópodes',
            '596': 'Cordados',
            '597': 'Vertebrados de sangue frio; Peixes',
            '598': 'Aves',
            '599': 'Mamíferos',

            '600': 'Tecnologia e ciências aplicadas',
            '601': 'Filosofia e teoria (Tecnologia)',
            '602': 'Miscelânea (Tecnologia)',
            '603': 'Dicionários e Enciclopédias (Tecnologia)',
            '604': 'Tópicos especiais em Tecnologia',
            '605': 'Publicações em série (Tecnologia)',
            '606': 'Organizações (Tecnologia)',
            '607': 'Educação, pesquisa e tópicos relacionados em Tecnologia',
            '608': 'Invenções e patentes',
            '609': 'História, geografia e pessoas (Tecnologia)',
            '610': 'Medicina e saúde',
            '611': 'Anatomia humana, Citologia e Histologia',
            '612': 'Fisiologia humana',
            '613': 'Saúde pessoal e segurança',
            '613.907': 'Educação sexual',
            '614': 'Epidemiologia/Incidência e prevenção de doenças',
            '615': 'Farmacologia e terapêutica',
            '616': 'Doenças',
            '617': 'Cirurgia & especialidades médicas relacionadas',
            '618': 'Ginecologia, obstetrícia, pediatria e geriatria',
            '618.20835': 'Gravidez na adolescência',
            '618.9285882': 'Autismo infantil',
            '620': 'Engenharia e Operações aliadas',
            '621': 'Física Aplicada',
            '622': 'Mineração & Operações relacionadas',
            '623': 'Engenharia militar e náutica',
            '624': 'Engenharia civil',
            '625': 'Engenharia ferroviária',
            '627': 'Engenharia hidráulica',
            '628': 'Engenharia sanitária e municipal',
            '629': 'Outros ramos da Engenharia',
            '630': 'Agricultura e tecnologias relacionadas',
            '631': 'Técnicas, equipamentos e materiais (Agricultura)',
            '632': 'Lesões, doenças de plantas e pragas',
            '633': 'Campo & plantação',
            '634': 'Pomares, frutas e Silvicultura',
            '635': 'Horticultura e plantações em jardins',
            '636': 'Criação de animais',
            '637': 'Processamento de laticínios e produtos relacionados',
            '638': 'Cultura de Insetos',
            '639': 'Caça, pesca e conservação',
            '640': 'Gestão da casa e da família',
            '641': 'Comidas e bebidas',
            '642': 'Refeições & serviços de mesa',
            '643': 'Habitação e equipamentos domésticos',
            '644': 'Utilidades domésticas',
            '645': 'Mobiliário para o lar',
            '646': 'Costura, vestuário e vida pessoal',
            '647': 'Gestão das habitações públicas',
            '648': 'Economia doméstica/Gerenciamento do lar',
            '649': 'Puericultura/Criação dos filhos e assistência domiciliar de pessoas',
            '650': 'Gestão e administração de negócios',
            '651': 'Serviços de escritório',
            '652': 'Processos de comunicação escrita',
            '653': 'Taquigrafia',
            '657': 'Contabilidade',
            '658': 'Gestão geral',
            '658.4038': 'Gestão da Informação',
            '658.450952': 'Comunicação nas Organizações',
            '658.8': 'Marketing',
            '659': 'Publicidade e Relações Públicas',
            '660': 'Engenharia química',
            '661': 'Produtos químicos industriais',
            '662': 'Explosivos, combustíveis e produtos relacionados',
            '663': 'Tecnologia de bebidas',
            '664': 'Engenharia de Alimentos',
            '665': 'Óleos industriais, gorduras, ceras e gases',
            '666': 'Cerâmica e tecnologias aliadas',
            '667': 'Tecnologias de Limpeza, cor & revestimento',
            '668': 'Tecnologia de outros produtos orgânicos',
            '669': 'Metalurgia (Ramo da Ciência e Tecnologia que trata das propriedades dos metais, sua produção e purificação)',
            '670': 'Manufatura',
            '671': 'Metalurgia e produtos primários de metal (Fabricação dos materiais em metal)',
            '672': 'Ferro, aço e outras ligas de ferro',
            '673': 'Metais não-ferrosos',
            '674': 'Processamento de madeira, produtos de madeira e cortiça',
            '675': 'Couro & Processamento do couro e peles de animais',
            '676': 'Celulose & Tecnologia do papel',
            '677': 'Têxteis',
            '678': 'Elastômeros e produtos elastômeros',
            '679': 'Outros produtos de materiais específicos',
            '680': 'Fabricação para usos específicos',
            '681': 'Instrumentos de Precisão e outros dispositivos',
            '682': 'Pequenos trabalhos de forja (Ferraria)',
            '683': 'Equipamentos e eletrodomésticos',
            '684': 'Móveis e oficinas de casa',
            '685': 'Couro, pele e produtos relacionados',
            '686': 'Impressão e atividades relacionadas',
            '687': 'Vestuário e acessórios',
            '688': 'Outros produtos finais e embalagens',
            '690': 'Construção e obras públicas',
            '691': 'Materiais de construção',
            '692': 'Construção auxiliares práticas',
            '693': 'Materiais específicos e objetivos',
            '694': 'Construção de madeira e carpintaria',
            '695': 'Construção de cobertura e telhado',
            '696': 'Utilidades',
            '697': 'Aquecimento, ventilação e ar-condicionado',
            '698': 'Detalhes de acabamento',

            '700': 'Artes; artes plásticas e decorativas',
            '701': 'Filosofia das artes plásticas e decorativas',
            '702': 'Miscelânea das artes plásticas e decorativas',
            '703': 'Dicionários de artes plásticas e decorativas',
            '704': 'Tópicos Especiais em artes plásticas e decorativas',
            '705': 'Publicações seriadas de artes plásticas e decorativas',
            '706': 'Organizações e gestão (Artes)',
            '707': 'Educação, pesquisa e tópicos relacionados (Artes)',
            '708': 'Galerias, museus e coleções particulares',
            '709': 'Histórico, geografia e pessoas (Artes)',
            '710': 'Arte cívica & Paisagismo',
            '711': 'Planejamento de área',
            '712': 'Arquitetura paisagista',
            '713': 'Arquitetura paisagista de vias de tráfego',
            '714': 'Características da água',
            '715': 'Plantas lenhosas',
            '716': 'Plantas herbáceas',
            '717': 'Estruturas em arquitetura paisagista',
            '718': 'Design de paisagem dos cemitérios',
            '719': 'Paisagens naturais',
            '720': 'Arquitetura',
            '721': 'Estruturas arquitetônicas',
            '722': 'Arquitetura de 300 ac.',
            '723': 'Arquitetura de 300-1399 ac.',
            '724': 'Arquitetura de 1400',
            '725': 'Estruturas públicas',
            '726': 'Construções para fins religiosos',
            '727': 'Edifícios para educação e pesquisa',
            '727.8': 'Bibliotecas – Arquitetura',
            '728': 'Edifícios residenciais e relacionados',
            '729': 'Design & Decoração',
            '730': 'Artes plásticas; Escultura',
            '731': 'Processos, formas e temas da escultura',
            '732': 'Escultura de 500 a.c',
            '733': 'Escultura grega, etrusca e romana',
            '734': 'Escultura de 500-1399 a.c',
            '735': 'Escultura de 1400',
            '736': 'Entalhes & esculturas',
            '737': 'Numismática & Sigilografia',
            '738': 'Artes de cerâmica',
            '739': 'Artes de metais',
            '740': 'Desenhos e artes decorativas',
            '741': 'Desenhos e tirinhas',
            '742': 'Perspectiva',
            '743': 'Desenhos e desenhos por assunto',
            '745': 'Artes decorativas',
            '746': 'Artes têxteis',
            '747': 'Decoração de interiores',
            '748': 'Vidro',
            '749': 'Mobiliário e acessórios (Artes)',
            '750': 'Pintura e quadros',
            '751': 'Técnicas, equipamentos, materiais e formas (Artes)',
            '752': 'Cores',
            '753': 'Simbolismo, Alegoria, Mitologia e Lenda (Artes)',
            '754': 'Pinturas de gênero',
            '755': 'Religião (Artes)',
            '757': 'Figuras humanas',
            '758': 'Outros assuntos (Artes)',
            '759': 'Pintura e Pintores – Tratamento histórico e geográfico',
            '760': 'Artes gráficas; gravura e impressões',
            '761': 'Artes gráficas/Processos de relevo (Impressão de blocos)',
            '763': 'Processos de litografia',
            '764': 'Cromolitografia e serigrafia',
            '765': 'Gravação em Metal',
            '766': 'Gravação em Mezzo-tinto, água-tinta e processos relacionados',
            '767': 'Gravura a água forte & ponta seca (Drypoint)',
            '769': 'Gravura',
            '770': 'Fotografia, arte computacional, Cinematografia e Videografia',
            '771': 'Técnicas, equipamentos e materiais (Fotografia)',
            '772': 'Processos de sais metálicos',
            '773': 'Processos de impressão pigmentadas',
            '774': 'Holografia',
            '775': 'Fotografia digital',
            '776': 'Arte de computador (Arte digital)',
            '778': 'Campos e tipos de fotografia',
            '779': 'Fotógrafos',
            '780': 'Música',
            '781': 'Princípios gerais e formas musicais',
            '781.660981': 'Rock – Brasil',
            '782': 'Música vocal',
            '783': 'Música para vozes individuais; Voz',
            '784': 'Instrumentos e conjuntos instrumentais',
            '785': 'Conjuntos com um instrumento por parte',
            '786': 'Teclado e outros instrumentos',
            '787': 'Instrumentos de cordas',
            '788': 'Instrumentos de sopro',
            '789': '(Número opcional)',
            '790': 'Artes Recreativas e Cênicas',
            '790.07': 'Educação física escolar',
            '791': 'Apresentações públicas',
            '792': 'Apresentações de palco',
            '792.028': 'Representação teatral',
            '793': 'Jogos de salão & Entretenimento',
            '794': 'Jogos de salão de perícia e habilidade',
            '795': 'Jogos de azar',
            '796': 'Atletismo & esportes/exercícios ao ar livre & jogos',
            '796.0196': 'Educação física para crianças deficientes',
            '796.083': 'Educação física para crianças',
            '797': 'Esportes aquáticos e aéreos',
            '798': 'Equitação & Corrida de animais (Esporte)',
            '799': 'Pescaria, Caça & Tiro (Esporte)',

            '800': 'Literatura',
            '801': 'Filosofia e teoria em Literatura',
            '802': 'Miscelânea em Literatura',
            '803': 'Dicionários e Enciclopédias em Literatura',
            '805': 'Publicações em série (Literatura)',
            '806': 'Organizações e gestão em Literatura',
            '807': 'Educação, pesquisa e tópicos relacionados em Literatura',
            '808': 'Retórica e coleções de literatura',
            '808.80142': 'Classicismo',
            '809': 'História, descrição e críticas',
            '810': 'Literatura americana em Inglês',
            '811': 'Poesia norte-americana em Inglês',
            '812': 'Drama americano em Inglês',
            '813': 'Ficção americana em Inglês',
            '814': 'Redações americanas em Inglês',
            '815': 'Discursos americanos em Inglês',
            '816': 'Cartas americanas em Inglês',
            '817': 'Humor americano e sátira em Inglês',
            '818': 'Escritos americanos diversos',
            '819': '(Número opcional)',
            '820': 'Literatura britânica e anglófona',
            '821': 'Poesia inglesa',
            '822': 'Drama Inglês',
            '823': 'Ficção inglesa',
            '824': 'Ensaios Ingleses',
            '825': 'Discursos Ingleses',
            '826': 'Cartas Inglesas',
            '827': 'Humor e sátira inglesa',
            '828': 'Escritos ingleses diversos',
            '829': 'Literatura em Inglês Antigo (Anglo-saxão)',
            '830': 'Literaturas de línguas germânicas',
            '831': 'Poesia alemã',
            '832': 'Drama alemão',
            '833': 'Ficção alemã',
            '834': 'Ensaios alemães',
            '835': 'Discursos alemães',
            '836': 'Cartas alemãs',
            '837': 'humor e sátira alemã',
            '838': 'Escritos alemães diversos',
            '839': 'Outras literaturas germânicas',
            '840': 'Literaturas de língua francesa',
            '841': 'Poesia francesa',
            '842': 'Drama francês',
            '843': 'Ficção francesa',
            '844': 'Ensaios franceses',
            '845': 'Discursos franceses',
            '846': 'Cartas francesas',
            '847': 'Humor e sátira francesa',
            '848': 'Escritos franceses diversos',
            '849': 'Literatura occitana e catalã',
            '850': 'Literatura italiana, romena e outras relacionadas',
            '851': 'Poesia italiana',
            '852': 'Drama italiano',
            '853': 'Ficção italiana',
            '854': 'Ensaios italianos',
            '855': 'Discursos italianos',
            '856': 'Cartas italianos',
            '857': 'Humor e sátira italiana',
            '858': 'Escritos italianos diversos',
            '859': 'Literatura romena e relacionadas',
            '860': 'Literatura espanhola e portuguesa',
            '861': 'Poesia espanhola',
            '862': 'Drama espanhol',
            '863': 'Ficção Espanhol',
            '864': 'Ensaios espanhóis',
            '865': 'Discursos espanhóis',
            '866': 'Cartas espanholas',
            '867': 'Humor e sátira espanhol',
            '868': 'Escritos espanhóis diversos',
            'B869': 'Literatura brasileira',
            'B869.098131': 'Literatura cearense',
            'B869.301': 'Contos brasileiros',
            'P869': 'Literatura portuguesa',
            'P869.3': 'Ficção portuguesa',
            '870': 'Literatura latina; Literatura itálica',
            '871': 'Poesia latina',
            '872': 'Poesia dramática latina e drama',
            '873': 'Poesia épica latina e ficção',
            '874': 'Poesia lírica latina',
            '875': 'Discursos latinos',
            '876': 'Cartas latinas',
            '877': 'Humor e sátira latina',
            '878': 'Escritos latinos diversos',
            '879': 'Literaturas de outras línguas itálicas',
            '880': 'Literatura Helênica; Grego clássico',
            '881': 'Poesia grega clássica',
            '882': 'Poesia dramática grega clássica e drama',
            '883': 'Poesia épica grega clássica e ficção',
            '884': 'Poesia lírica grega clássica',
            '885': 'Discursos clássicos gregos',
            '886': 'Cartas gregas clássicas',
            '887': 'Humor e sátira grega',
            '888': 'Clássicos gregos escritos diversos',
            '889': 'Literatura grega moderna',
            '890': 'Literaturas de outras línguas',
            '891': 'Literaturas do Leste indo-européias & Celta',
            '892': 'Literaturas afro-asiáticas; Literaturas semíticas',
            '893': 'Literaturas afro-asiáticas não-semitas',
            '894': 'Literatura Altaica, Urálica, Hiperbórea e Dravidiana',
            '895': 'Literaturas do Leste e Sudeste da Ásia',
            '896': 'Literaturas africanas',
            '897': 'Literaturas nativas da América do Norte',
            '898': 'Literaturas nativas da América do Sul',
            '899': 'Literaturas austronesianas e outras relacionadas',

            '900': 'História e Geografia',
            '901': 'Filosofia e teoria (História e Geografia)',
            '902': 'Miscelânea (História e Geografia)',
            '903': 'Dicionários e Enciclopédias de História e Geografia',
            '904': 'Relatos coletados de eventos',
            '905': 'Publicações em série (História e Geografia)',
            '906': 'Organizações e gestão (História e Geografia)',
            '907': 'Educação, pesquisa e tópicos relacionados em História e Geografia',
            '908': 'História das civilizações',
            '909': 'História mundial',
            '910': 'Geografia e viagem',
            '911': 'Geografia histórica',
            '912': 'Atlas, mapas, cartas e plantas',
            '913': 'Geografia da viagem e do mundo antigo',
            '914': 'Geografia da viagem e na Europa',
            '915': 'Geografia da viagem e na Ásia',
            '916': 'Geografia da viagem e na África',
            '917': 'Geografia da viagem e na América do Norte',
            '918': 'Geografia da viagem e na América do Sul',
            '919': 'Geografia da viagem e em outras áreas',
            '920': 'Biografia, genealogia e insígnia',
            '921': 'Filósofos e psicólogos – Biografia',
            '921.7': 'Psicólogos – União Soviética – Biografia',
            '921.8494': 'Psicólogos suíços – Biografia',
            '922': 'Biografias de líderes religiosos, pensadores',
            '923': 'Biografias de pessoas nas ciências sociais',
            '924': 'Biografias de filólogos e lexicógrafos',
            '925': 'Biografia de cientistas',
            '926': 'Biografias de pessoas na tecnologia',
            '927': 'Biografias de pessoas nas artes e recreação',
            '928': 'Biografias de pessoas na literatura, história, biografia e genealogia',
            '929': 'Genealogia, nomes e insígnia',
            '930': 'História do mundo antigo até 499 a.c',
            '931': 'História da China até 420',
            '932': 'História do Egito até 640',
            '933': 'História da Palestina até 70',
            '934': 'História da Índia até 647',
            '935': 'História da Mesopotâmia e do Irã Planalto até 637',
            '936': 'História do Norte da Europa e Oeste da Itália até 499 a.c',
            '937': 'História da Itália e territórios adjacentes até 476',
            '938': 'História da Grécia até 323',
            '939': 'História de outras partes do mundo antigo até 640 a.c',
            '940': 'História da Europa',
            '941': 'História das Ilhas britânicas',
            '942': 'História da Inglaterra e País de Gales',
            '943': 'História da Europa Central; Alemanha',
            '944': 'História da França & Mônaco',
            '945': 'História da Península Italiana e ilhas adjacentes',
            '946': 'História da Península Ibérica e ilhas adjacentes',
            '947': 'História da Europa Oriental; Rússia',
            '948': 'História da Escandinávia',
            '949': 'História de outras partes da Europa',
            '950': 'História da Ásia; Extremo Oriente',
            '951': 'História da China e áreas adjacentes',
            '952': 'História do Japão',
            '953': 'História da Península Arábica e áreas adjacentes',
            '954': 'História do Sul da Ásia; Índia',
            '955': 'História do Irã',
            '956': 'História do Oriente Médio',
            '957': 'História da Sibéria (Rússia asiática)',
            '958': 'História da Ásia Central',
            '959': 'História do Sudeste Asiático',
            '960': 'História da África',
            '961': 'História da Tunísia e Líbia',
            '962': 'História do Egito e Sudão',
            '963': 'História da Etiópia e Eritreia',
            '964': 'História da Costa Africana Noroeste e Ilhas do Mar alto',
            '965': 'História da Argélia',
            '966': 'História da África Ocidental e Ilhas do Mar alto',
            '967': 'História da África Central e Ilhas',
            '968': 'História da África do Sul; República da África do Sul',
            '969': 'História das Ilhas do Sul do Oceano Índico',
            '970': 'História da América do Norte',
            '971': 'História do Canadá',
            '972': 'História da América Central; México',
            '973': 'História dos Estados Unidos',
            '974': 'Nordeste dos Estados Unidos',
            '975': 'Sudeste dos Estados Unidos',
            '976': 'Sul central dos Estados Unidos',
            '977': 'Norte central dos Estados Unidos',
            '978': 'Oeste dos Estados Unidos',
            '979': 'Grande Bacia & Região da encosta do Pacífico',
            '980': 'História da América do Sul',
            '981': 'História do Brasil',
            '981.01': 'História do Brasil até 1533',
            '981.04': 'História do Brasil, Período imperial (1822-1889)',
            '981.06': 'História do Brasil, 1930',
            '981.061': 'História do Brasil, 1945-1955',
            '982': 'História da Argentina',
            '983': 'História do Chile',
            '984': 'História da Bolívia',
            '985': 'História do Peru',
            '986': 'História da Colômbia e Equador',
            '987': 'História da Venezuela',
            '988': 'História da Guiana',
            '989': 'História do Paraguai e Uruguai',
            '990': 'História geral de outras regiões',
            '993': 'História da Nova Zelândia',
            '994': 'História da Austrália',
            '995': 'História da Melanésia; Nova Guiné',
            '996': 'História de outras partes do Pacífico; Polinésia',
            '997': 'Ilhas do Oceano Atlântico',
            '998': 'Ilhas do Ártico e Antártica',
            '999': 'Mundos extraterrestres',
        };

        const cddToGenreDec = {
            '00': 'Generalidades',
            '01': 'Bibliografia',
            '02': 'Biblioteca & Ciências da Informação',
            '03': 'Obras enciclopédicas Gerais',
            '05': 'Publicações seriadas em geral',
            '06': 'Organizações Gerais e Museologia',
            '07': 'Notícias da mídia, jornalismo e editoração',
            '08': 'Coleções gerais',
            '09': 'Manuscritos e livros raros',

            '10': 'Filosofia',
            '11': 'Metafísica',
            '12': 'Epistemologia, causalidade e humanidade',
            '13': 'Parapsicologia e ocultismo',
            '14': 'Escolas filosóficas específicas',
            '15': 'Psicologia',
            '16': 'Lógica',
            '17': 'Ética',
            '18': 'Filosofia antiga e medieval',
            '19': 'Filosofia ocidental moderna',
            
            '20': 'Religião',
            '21': 'Filosofia e Teoria da religião',
            '22': 'Bíblia',
            '23': 'Cristianismo e Teologia cristã',
            '24': 'Teologia moral e devocional cristã',
            '25': 'Prática cristã & Igrejas locais',
            '26': 'Teologia social e eclesiástica',
            '27': 'História do Cristianismo e da Igreja cristã',
            '28': 'Denominações cristãs e seitas',
            '29': 'Outras religiões',

            '30': 'Ciências Sociais',
            '31': 'Estatísticas Gerais',
            '32': 'Ciência Política',
            '33': 'Economia',
            '34': 'Direito',
            '35': 'Administração Pública e Ciência Militar',
            '36': 'Problemas sociais, serviços e associações',
            '37': 'Educação',
            '38': 'Comércio, comunicação e transporte',
            '39': 'Costumes, etiqueta e folclore',

            '40': 'Linguagem & Idiomas',
            '41': 'Linguística geral',
            '42': 'Língua inglesa',
            '43': 'Línguas germânicas; Alemão',
            '44': 'Línguas românicas; Francês',
            '45': 'Língua italiana, romena e outras relacionadas',
            '46': 'Língua espanhola e Português',
            '47': 'Línguas itálicas; Línguas latinas; Latim',
            '48': 'Línguas helênicas; Grego clássico',
            '49': 'Outros idiomas',

            '50': 'Ciências Naturais e Matemáticas',
            '51': 'Matemática',
            '52': 'Astronomia e ciências relacionadas',
            '53': 'Física',
            '54': 'Química e ciências relacionadas',
            '55': 'Ciências da Terra e Geociências',
            '56': 'Paleontologia; Paleozoologia',
            '57': 'Ciências da vida; Biologia',
            '58': 'Plantas (Botânica)',
            '59': 'Animais (Zoologia)',

            '60': 'Tecnologia e ciências aplicadas',
            '61': 'Medicina e saúde',
            '62': 'Engenharia e Operações aliadas',
            '63': 'Agricultura e tecnologias relacionadas',
            '64': 'Gestão da casa e da família',
            '65': 'Gestão e administração de negócios',
            '66': 'Engenharia química',
            '67': 'Manufatura',
            '68': 'Fabricação para usos específicos',
            '69': 'Construção e obras públicas',

            '70': 'Artes; artes plásticas e decorativas',
            '71': 'Arte cívica & Paisagismo',
            '72': 'Arquitetura',
            '73': 'Artes plásticas; Escultura',
            '74': 'Desenhos e artes decorativas',
            '75': 'Pintura e quadros',
            '76': 'Artes gráficas; gravura e impressões',
            '77': 'Fotografia, arte computacional, Cinematografia e Videografia',
            '78': 'Música',
            '79': 'Artes Recreativas e Cênicas',

            '80': 'Literatura',
            '81': 'Literatura americana em Inglês',
            '82': 'Literatura britânica e anglófona',
            '83': 'Literaturas de línguas germânicas',
            '84': 'Literaturas de língua francesa',
            '85': 'Literatura italiana, romena e outras relacionadas',
            '86': 'Literatura espanhola e portuguesa',
            '87': 'Literatura latina; Literatura itálica',
            '88': 'Literatura Helênica; Grego clássico',
            '89': 'Literaturas de outras línguas',

            '90': 'História e Geografia',
            '91': 'Geografia e viagem',
            '92': 'Biografia, genealogia e insígnia',
            '93': 'História do mundo antigo até 499 a.c',
            '94': 'História da Europa',
            '95': 'História da Ásia; Extremo Oriente',
            '96': 'História da África',
            '97': 'História da América do Norte',
            '98': 'História da América do Sul',
            '99': 'História geral de outras regiões',
        };

        // Adiciona um evento de input ao campo de CDD
        cddInput.addEventListener('input', () => {
        
        const cddValue = cddInput.value.trim();// Obtém o valor exato do campo de CDD


        if (cddValue in cddToGenre) { //Se acha a correspondência exata de CDD
            genreInput.value = cddToGenre[cddValue]; // Preenche o gênero com o valor correspondente
        }
        else { //Se não...
            const cddValueInt = cddInput.value.slice(0, 3);
            if(cddValueInt in cddToGenre){//...verifica se os 3 primeiros dígitos estão na lista
                                          //Aqui é onde a maioria dos CDDs inseridos irão se encaixar
                                          
                genreInput.value = cddToGenre[cddValueInt];
            }
            else { //Se não...
                const cddValueDec = cddInput.value.slice(0, 2);
                if (cddValueDec in cddToGenreDec) { //verifica qual a classificaçao geral do CDD inserido (ex.:se não houver o 891, considera como 890)
                                                    //Este é para o caso de algum CDD inteiro inserido não esteja cadastrado

                    genreInput.value = cddToGenreDec[cddValueDec];
                }
                else{
                    genreInput.value = '';
                }
            }
        
        }
        });